words = [
    'abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom',
    'azure', 'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz',
    'blizzard', 'boggle', 'bookworm', 'boxcar', 'boxful', 'buckaroo', 'buffalo',
    'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords', 'caliph', 'cobweb',
    'croquet', 'crypt', 'curacao', 'daiquiri', 'dirndl', 'disavow', 'dizzying',
    'duplex', 'dwarves', 'embezzle', 'equip', 'espionage', 'euouae', 'exodus',
    'fjord', 'flapjack', 'flopping', 'fluffiness', 'flyby', 'fuchsia', 'gizmo',
    'glowworm', 'glyph', 'gnarly', 'gnostic', 'gossip', 'grogginess', 'haiku',
    'haphazard', 'hyphen', 'iatrogenic', 'icebox', 'injury', 'ivory', 'jackpot',
    'jaundice', 'jawbreaker', 'jazziest', 'jazzy', 'jigsaw', 'jinx', 'jiujitsu',
    'jockey', 'jogging', 'joking', 'jovial', 'joyful', 'juicy', 'jukebox',
    'jumbo', 'kayak', 'kazoo', 'keyhole', 'khaki', 'kilobyte', 'kiosk', 'kitsch',
    'kiwifruit', 'klutz', 'larynx', 'lengths', 'lucky', 'luxury', 'lymph',
    'marquis', 'matrix', 'megahertz', 'microwave', 'mnemonic', 'mystify', 'naphtha',
    'nightclub', 'nowadays', 'numbskull', 'nymph', 'onyx', 'ovary', 'oxidize',
    'oxygen', 'pajama', 'peekaboo', 'phlegm', 'pixel', 'pneumonia', 'polka',
    'pshaw', 'psyche', 'puppy', 'puzzling', 'quartz', 'queue', 'quixotic', 'quiz',
    'quorum', 'razzmatazz', 'rhubarb', 'rhythm', 'rickshaw', 'schnapps', 'scratch',
    'shiv', 'snazzy', 'sphinx', 'spritz', 'squawk', 'staff', 'strength',
    'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel', 'syndrome',
    'thriftless', 'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant',
    'triphthong', 'twelfth', 'twelfths', 'unknown', 'unworthy', 'unzip', 'uptown',
    'vaporize', 'vixen', 'vodka', 'voodoo', 'vortex', 'voyeurism', 'walkway',
    'waltz', 'wave', 'wavy', 'waxy', 'wellspring', 'whiskey', 'whizzing', 'wimpy',
    'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern', 'xylophone', 'yippee',
    'yoked', 'youthful', 'yummy', 'zephyr', 'zigzag', 'zigzagging', 'zilch',
    'zipper', 'zodiac', 'zombie', "Happy", "Sunny", "Laugh", "Smile", "Playful", "Gentle", "Breeze", "Cozy",
    "Simple", "Friendly", "Quiet", "Calm", "Jolly", "Easy", "Kind", "Brave",
    "Hope", "Cheer", "Snuggle", "Radiant", "Lively", "Sweet", "Soft", "Cheerful",
    "Glee", "Tender", "Pure", "Delight", "Wholesome", "Fresh", "Grace",
    "Soothe", "Ample", "Mirth", "Merry", "Serene", "Bountiful", "Tranquil",
]
